name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build gateway image
        run: docker build -t ghcr.io/sedimentt/quickticket-gateway:${{ github.sha }} ./app/gateway
      - name: Build events image
        run: docker build -t ghcr.io/sedimentt/quickticket-events:${{ github.sha }} ./app/events
      - name: Build payments
        run: docker build -t ghcr.io/sedimentt/quickticket-payments:${{ github.sha }} ./app/payments
      - name: Push gateway image
        run: docker push ghcr.io/sedimentt/quickticket-gateway:${{ github.sha }}
      - name: Push events image
        run: docker push ghcr.io/sedimentt/quickticket-events:${{ github.sha }}
      - name: Push payments image
        run: docker push ghcr.io/sedimentt/quickticket-payments:${{ github.sha }}
